### PR TITLE
Show attachments within investigation prompts and reports

### PR DESCRIPTION
**Pull request by KojiOdyssey**
Draft pull request for issue #135

### CODE REVIEW

**Comment by KojiOdyssey** [comment]
wtf did i do

**Comment by itsWindows11** [comment]
> wtf did i do

accidental action maybe?

**Comment by KojiOdyssey** [comment]
> > wtf did i do
> 
> accidental action maybe?

maybe, im not very good with github tbh

**Comment by KojiOdyssey** [comment]
I'm just going to close this considering how messed up it is. I will create a new one when ready.

**Pull request closed without merging**
