### PR TITLE
Fix empty embed field value error when reporting attachment

### PR DESCRIPTION
**Pull request by KojiOdyssey**
### Before:
image
### After:
image

### CODE REVIEW

**Comment by KojiOdyssey** [comment]
image

**Review by itsWindows11 — APPROVED** [review]
Looks good!

**Comment by Jasius** [comment]
@lost-in-action could you take a look at this? This is your code so you may understand better if these changes might have any negative consequences, I'll do some testing myself too once my time frees up.

**Review by Jasius — APPROVED** [review]
There was one part which was breaking the feature entirely, but now it is fixed and everything functions as expected. Also added some visual changes.

**Pull request merged**
