### PR TITLE
Ban command improvements

### LINKED ISSUE #40: /ban command improvements
- [ ] Send a DM to the user who is getting banned before the ban, so that they're aware why server is gone from their servers list.

- [ ] Add ability to add preset message which would be appended to a DM which gets dispatched to a banee

- [ ] Roles hierarchy check to prevent users kicking someone who're inline or above them in hierarchy.

### PR DESCRIPTION
**Pull request by itsWindows11**
Resolves #40

This includes role hierarchy checks, more simplified code and a DM before the ban

### CODE REVIEW

**Review by dongle-the-gadget — CHANGES_REQUESTED** [review]
I don't see code for role hierarchy, can you double check?

**Comment by itsWindows11** [comment]
@dongle-the-gadget look at line 33, especially where it has this

```
interaction.options.getMember('user').manageable
```

This basically checks if a member is manageable, like if their role is higher than yours, could you ban them or not.

**Comment by dongle-the-gadget** [comment]
@itsWindows11 From the discord.js documentation, that only checks if the client user (bot) is higher than the target, it doesn't necessary check if the user running the command is higher than the target.

**Comment by itsWindows11** [comment]
> @itsWindows11 From the discord.js documentation, that only checks if the client user (bot) is higher than the target, it doesn't necessary check if the user running the command is higher than the target.

I know lol, but still that's intended

**Comment by dongle-the-gadget** [comment]
> > @itsWindows11 From the discord.js documentation, that only checks if the client user (bot) is higher than the target, it doesn't necessary check if the user running the command is higher than the target.
> 
> I know lol, but still that's intended

Well Discord doesn't allow equal members to ban each other, and also why use the word "you" when the bot doesn't have sufficient perm.

**Comment by itsWindows11** [comment]
> > > @itsWindows11 From the discord.js documentation, that only checks if the client user (bot) is higher than the target, it doesn't necessary check if the user running the command is higher than the target.
> > 
> > 
> > I know lol, but still that's intended
> 
> Well Discord doesn't allow equal members to ban each other, and also why use the word "you" when the bot doesn't have sufficient perm.

Did I even use "you" anywhere? Try to refresh the page

**Comment by dongle-the-gadget** [comment]
> > > > @itsWindows11 From the discord.js documentation, that only checks if the client user (bot) is higher than the target, it doesn't necessary check if the user running the command is higher than the target.
> > > 
> > > 
> > > I know lol, but still that's intended
> > 
> > 
> > Well Discord doesn't allow equal members to ban each other, and also why use the word "you" when the bot doesn't have sufficient perm.
> 
> Did I even use "you" anywhere? Try to refresh the page

image

**Comment by itsWindows11** [comment]
> > > > > @itsWindows11 From the discord.js documentation, that only checks if the client user (bot) is higher than the target, it doesn't necessary check if the user running the command is higher than the target.
> > > > 
> > > > 
> > > > I know lol, but still that's intended
> > > 
> > > 
> > > Well Discord doesn't allow equal members to ban each other, and also why use the word "you" when the bot doesn't have sufficient perm.
> > 
> > 
> > Did I even use "you" anywhere? Try to refresh the page
> 
> image

Oh noes, that may actually cause some bugs from my understanding

**Comment by dongle-the-gadget** [comment]
@itsWindows11 shouldn't Dotsimus also check its hierarchy?

**Comment by itsWindows11** [comment]
> @itsWindows11 shouldn't Dotsimus also check its hierarchy?

No, actually if there was a failed ban or Dotsimus doesn't have enough perms then the error resulted would get catched and then it will tell you if it can't ban the user.

**Comment by dongle-the-gadget** [comment]
> > @itsWindows11 shouldn't Dotsimus also check its hierarchy?
> 
> No, actually if there was a failed ban or Dotsimus doesn't have enough perms then the error resulted would get catched and then it will tell you if it can't ban the user.

> Oh snap! Something went horribly wrong, check whether bot has required permissions enabled.

?

**Review by dongle-the-gadget — APPROVED** [review]

**Review by Jasius — APPROVED** [review]

**Pull request merged**
